# Week 2 Mini-project.

### Imports
Importing all the necessary modules.

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, RidgeCV
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from collections import Counter

### Loading and EDA on the dataset, finding out it's charateristics.

In [49]:
df = pd.read_csv('CleanAmes.csv')

In [50]:
# Tests
pd.set_option('display.max_columns', 100)
df.head(2)

,Unnamed: 0,MS SubClass,Lot Frontage,Lot Area,Neighborhood,Overall Qual,Year Built,Year Remod/Add,Exterior 1st,Exterior 2nd,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,TotRms AbvGrd,Garage Yr Blt,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Sale Type,SalePrice
0,0,20,141.0,31770,NAmes,6,1960,1960,BrkFace,Plywood,112.0,639.0,0.0,441.0,1080.0,1656,0,0,1656,7,1960.0,528.0,210,62,0,0,0,0,0,5,WD,215000
1,1,20,80.0,11622,NAmes,5,1961,1961,VinylSd,VinylSd,0.0,468.0,144.0,270.0,882.0,896,0,0,896,5,1961.0,730.0,140,0,0,0,120,0,0,6,WD,105000

In [ ]:
df['age'] = 2006 - df['Year Built']
df['from_remod'] = 2006 - df['Year Remod/Add']
df.drop(columns=['Year Built', 'Year Remod/Add'], inplace=True)
df = df.dropna()
df['SalePrice'] = np.log1p(df['SalePrice'])
X = df.drop(['SalePrice', 'Sale Type'], axis=1)
y = df['SalePrice']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [57]:
enc_cols = ['Neighborhood', 'Exterior 1st', 'Exterior 2nd', 'MS SubClass']
scl_cols = ['Lot Frontage', 'Lot Area', 'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Garage Yr Blt', 'Garage Area', 'Wood Deck SF', 'Open Porch SF']

encode = Pipeline([
    ('encode', OneHotEncoder(sparse_output=False, handle_unknown='ignore'))
])

scale = Pipeline([
    ('ss', StandardScaler())
])

prep = ColumnTransformer([
    ('enc', encode, enc_cols),
    ('scl', scale, scl_cols)
],
    remainder='passthrough')

pipeline = Pipeline([
    ('prep', prep), 
    ('lr', RidgeCV(alphas=np.array(range(5)), cv=5))
])

In [58]:

pipeline.fit(X_train, y_train)
pred = pipeline.predict(X_test)
r2 = r2_score(y_test, pred)
scores = cross_val_score(pipeline, X, y, cv=5)

In [59]:
scores

array([0.86645926, 0.90824895, 0.80815288, 0.77469774, 0.90412159])

In [35]:
scores

array([0.86323025, 0.89221247, 0.80006218, 0.74913116, 0.87794954])

In [7]:
X_train

,Unnamed: 0,MS SubClass,Lot Frontage,Lot Area,Neighborhood,Overall Qual,Year Built,Year Remod/Add,Exterior 1st,Exterior 2nd,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,TotRms AbvGrd,Garage Yr Blt,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Sale Type
1655,1655,60,80.0,10793,NWAmes,5,1969,1969,WdShing,HdBoard,263.0,493.0,287.0,0.0,780.0,780,840,0,1620,7,1969.0,462.0,208,0,0,0,0,0,0,4,WD
962,962,20,130.0,11457,Timber,6,1988,1988,HdBoard,HdBoard,0.0,1005.0,0.0,387.0,1392.0,1412,0,0,1412,6,1988.0,576.0,0,0,169,0,0,0,0,3,WD
2414,2414,60,58.0,14054,Gilbert,7,2006,2006,VinylSd,VinylSd,0.0,0.0,0.0,879.0,879.0,879,984,0,1863,9,2006.0,660.0,100,17,0,0,0,0,0,11,New
1480,1480,60,63.0,8199,CollgCr,7,2005,2005,WdShing,Wd Shng,0.0,648.0,0.0,80.0,728.0,728,728,0,1456,7,2005.0,410.0,36,18,0,0,0,0,0,10,WD
1400,1400,20,82.0,20270,ClearCr,7,1979,1979,Plywood,Plywood,0.0,599.0,0.0,925.0,1524.0,1524,0,0,1524,7,1979.0,478.0,140,0,0,0,0,0,0,4,WD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2120,2120,20,65.0,8775,CollgCr,5,1994,1994,VinylSd,VinylSd,0.0,495.0,0.0,495.0,990.0,990,0,0,990,5,1996.0,299.0,0,64,0,0,0,0,0,4,WD
1890,1890,20,80.0,8800,NAmes,7,1966,1966,HdBoard,Plywood,202.0,654.0,0.0,520.0,1174.0,1200,0,0,1200,6,1966.0,440.0,0,0,0,0,0,0,0,10,CWD
1178,1178,120,38.0,14963,Veenker,8,1996,1996,BrkFace,BrkFace,0.0,786.0,0.0,474.0,1260.0,1288,0,0,1288,4,1996.0,500.0,120,30,0,0,224,0,0,12,WD
1078,1078,160,36.0,2448,NridgHt,7,2003,2004,VinylSd,Wd Shng,106.0,573.0,0.0,191.0,764.0,764,862,0,1626,6,2003.0,474.0,0,27,0,0,0,0,0,10,WD
1831,1831,20,43.0,12712,Sawyer,6,1973,2006,CemntBd,CmentBd,0.0,968.0,0.0,76.0,1044.0,1055,0,0,1055,5,1973.0,542.0,455,0,0,0,0,0,0,1,WD

In [36]:

col_list = df.columns
df = df.dropna()

In [ ]:
## Don't run this again
# features = [col for col in col_list if df[col].nunique() < 10]
# df.drop(columns=features, inplace=True)
# df.drop(columns=['Order', 'PID'], inplace=True)

In [32]:
str_cols = df[['Neighborhood', 'Exterior 1st', 'Exterior 2nd', 'MS SubClass', 'Sale Type']]
ohe = OneHotEncoder(sparse_output=False)

encoded = ohe.fit_transform(str_cols)
cols = ohe.get_feature_names_out()
newdf = pd.DataFrame(
    encoded,
    columns=cols
)

df = pd.concat([df.drop(columns=str_cols), newdf],axis=1)

In [ ]:
X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

In [55]:
df.columns[df.isnull().sum()>0]

Index(['Lot Frontage', 'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Garage Yr Blt', 'Garage Area'],
      dtype='str')

In [39]:
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.8103117248327872

In [8]:
# Neighborhood, Exterior 1st, Exterior 2nd <-- String dtype Columns. 
# plt.scatter(X['Gr Liv Area'], y)
# plt.xlim(0, 4000)
# # plt.ylim(0, 5000000)
# plt.show()
# col_list